### ISSUE TITLE
Se pueden poner bloques dentro de la scorebox

### ISSUE THREAD

**Issue by vYuri** [vYuri/Maps-Xml#8]
Aun se pueden poner bloques, helpppppppppp :P

**Comment by AngelCasillas01** [comment]
Como dije, arreglare esto cuando vuelva de viaje,ya tengo en mente que pondre 😉

**Comment by vYuri** [comment]
En realidad, estaba funcionando y de la nada no funciono más. Así que no sé :P

**Comment by AngelCasillas01** [comment]
@vYuri restartea el server, igual creo que se como editarlo y que funcione, pero necesito mi pc y nose cuando llegue 😢

**Comment by AngelCasillas01** [comment]
#5

**Comment by AngelCasillas01** [comment]
Closing this because there is an identical issue
